### ISSUE TITLE
I'm in China, "data" always prompts download error

### ISSUE THREAD

**Issue by yang-zhuang** [uclanlp/synpg#3]
Hello, I am in China. When I click the link "data" to download the data, I always get a download error when it reaches 500M. Could you please provide the original webpage for downloading data, and then I can download it from the corresponding webpage, or can you provide the link of Baidu net disk?

**Comment by ej0cl6** [comment]
Since the data is large, we think google drive is the best way to share the data. We will consider building a specific project webpage in the future.
