### ISSUE TITLE
Data preprocessing

### ISSUE THREAD

**Issue by tomhosking** [uclanlp/synpg#4]
Hi,

Could you please provide the command you used to generate the parses to use as input, as well as any other preprocessing steps required? I have some data that I would like to test your system on, how should I generate an input file in the correct format?

Thanks!

**Comment by ej0cl6** [comment]
Hi, we use Stanford CoreNLP with the following command

    java -Xmx12g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLP -threads 1 -annotators tokenize,ssplit,pos,parse -ssplit.eolonly -filelist files.txt -outputFormat text -parse.model edu/stanford/nlp/models/srparser/englishSR.ser.gz -outputDirectory ./output/

You can refer to https://nlp.stanford.edu/software/srparser.html for more details.

**Comment by tomhosking** [comment]
Thanks!
