### ISSUE TITLE
Selecting top-1 output

### ISSUE THREAD

**Issue by tomhosking** [uclanlp/synpg#5]
The generation script gives 4 candidates outputs for each input - what is the "correct" way to select the preferred top-1 output? Is it simply the first generated output?

**Comment by ej0cl6** [comment]
These 4 outputs are corresponding to the input syntactic guidance in https://github.com/uclanlp/synpg/blob/master/generate.py#L47

In this work, we just focus on how to let the model follows the syntactic guidance and leave scoring outputs for future work. Currently, users have to manually choose the appropriate templates and outputs.

**Comment by tomhosking** [comment]
Thanks, that makes sense. For the scores reported in the paper, where are the templates sourced from? Do you use the (pruned) parse of the target as the input template, or is there a set of candidates used for each dataset?
